const form=document.querySelector('#brief');const results=document.querySelector('#results');const move=document.querySelector('#move');move.min=new Date().toISOString().slice(0,10);
function escapeHtml(value){return String(value).replace(/[&<>"']/g,char=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[char]));}
form.addEventListener('submit',event=>{event.preventDefault();if(!form.reportValidity())return;
 const type=document.querySelector('#type').value,budget=Number(document.querySelector('#budget').value),date=move.value,duration=document.querySelector('#duration').value,area=document.querySelector('#area').value,rooms=document.querySelector('#rooms').value,features=[...form.querySelectorAll('input[type=checkbox]:checked')].map(x=>x.value);
 const dateLabel=new Intl.DateTimeFormat('en-GB',{day:'numeric',month:'short',year:'numeric'}).format(new Date(date+'T12:00:00'));
 const brief=[type,rooms==='Flexible'?'flexible bedrooms':rooms+' bedroom'+(rooms==='1'?'':'s'),'up to €'+budget.toLocaleString('en-US')+'/month',area,'from '+dateLabel,duration].join(' · ');
 const examples=[{name:'Essential search',fee:'€390 example fee',lead:'Focused shortlist',detail:'A concise set of homes matching your budget and dates, with a viewing plan you can follow yourself.'},{name:'Guided viewings',fee:'€690 example fee',lead:'Search + coordination',detail:'A wider search with a proposed viewing schedule and help comparing the practical details of each property.'},{name:'Relocation support',fee:'€990 example fee',lead:'Extended arrival help',detail:'A search plan that also considers commute, local services and the move-in checklist.'}];
 results.innerHTML='<div class="summary"><span class="status">FICTIONAL SEARCH BRIEF</span><br>'+escapeHtml(brief)+(features.length?'<br><b>Must-haves:</b> '+features.map(escapeHtml).join(', '):'')+'</div>'+examples.map((p,i)=>'<article class="proposal"><div class="status">SAMPLE PROPOSAL 0'+(i+1)+'</div><h3>'+p.name+'</h3><p>'+p.detail+'</p><div class="meta"><span>'+p.lead+'</span><strong>'+p.fee+'</strong></div></article>').join('')+'<p class="privacy">These are illustrative service concepts, not offers from agents. No request was sent.</p>';
 results.scrollIntoView({behavior:'smooth',block:'nearest'});
});
